### ISSUE TITLE
meta: Investigate various Continous Integration services

### ISSUE THREAD

**Issue by mewmew** [mewpaper/decompilation#4]
Investigate [which](https://jmcvetta.github.io/blog/2013/08/30/continuous-integration-for-go-code/) Continuous Integration services to use for:
- [x] _2014-09-21_: [build status](https://travis-ci.org/) for commits and pull requests (SUCCESS/FAILURE)
- [x] _2014-09-21_: [test cases](https://travis-ci.org/) (PASS/FAIL)
- [x] _2014-09-21_: [code coverage](https://coveralls.io/) (percentage)
- [ ] benchmarks? (percentage delta)
